services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: node:20
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      SHELL: /bin/bash # Fix chokidar-cli error
    volumes:
      - .:/app
