version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./repos:/srv/git
      - ./git-server/authorized_keys:/authorized_keys
    command: [ "npm", "start" ]
    depends_on:
      - git-server

  git-server:
    build:
      context: ./git-server
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    volumes:
      - ./repos:/srv/git
      - ./git-server/hooks:/etc/git-hooks
      - ./git-server/authorized_keys:/authorized_keys
    extra_hosts:
      - "host.docker.internal:host-gateway"
