services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data/solid:/app/data
      - ./data/repos:/srv/git
      - ./data/integrations:/app/integrations
      - ./data/authorized_keys:/authorized_keys
      - ./data/general-logs:/app/general-logs
      - ./data/integrations-meta:/app/integrations-meta
    depends_on:
      - git-server

  git-server:
    build:
      context: ./git-server
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    volumes:
      - ./data/repos:/srv/git
      - ./git-server/hooks:/etc/git-hooks
      - ./data/authorized_keys:/authorized_keys
