version: '3.8'
services:
  node-app:
    platform: linux/amd64
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./ui:/app/ui
      - ./dist:/app/dist
    command: [ "npm", "run", "watch" ]
