#!/bin/bash

while read oldrev newrev refname
do
  curl -X POST http://node-app:3000/git-commit-hook \
       -H "Content-Type: application/json" \
       -d "{\"repo\": \"$PWD\", \"ref\": \"$refname\", \"oldrev\": \"$oldrev\", \"newrev\": \"$newrev\"}"
done